# Generated by Django 4.2.7 on 2023-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='about/image')),
                ('slide', models.ImageField(blank=True, upload_to='about/slide')),
                ('text_title', models.CharField(blank=True, max_length=255)),
                ('text_sub_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='customer/image')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('about', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='home/image')),
                ('slide', models.ImageField(blank=True, upload_to='home/slide')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('icons', models.ImageField(blank=True, upload_to='service/image')),
                ('icons_title', models.CharField(blank=True, max_length=255)),
                ('icons_sub_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('person_photo', models.ImageField(blank=True, upload_to='team/photos')),
                ('person_name', models.CharField(blank=True, max_length=255)),
                ('person_business', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('icons', models.ImageField(blank=True, upload_to='why/image')),
                ('icons_title', models.CharField(blank=True, max_length=255)),
                ('icons_sub_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'WhyChoose',
                'verbose_name_plural': 'WhyChooses',
            },
        ),
    ]
